[project]
name = "3d"
version = "0.1.0"
description = ""
authors = [
    {name = "Yu Taek Lee",email = "lcpnine@gmail.com"}
]
readme = "README.md"
requires-python = "3.10.19"
dependencies = [
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
